# 异常捕获与处理

## 1. 异常

Java 将异常分为两种，`Checked 异常`和 `Runtime 异常`。

> + Checked 异常：编译阶段发现的异常；
> + Runtime 异常：

## 2. 异常处理机制

Java 的异常处理机制主要依赖于 `try`、`catch`、`finally`、`throw` 和 `throws` 五个关键字。

### 2.1 使用try/catch捕获异常

Java 程序在运行过程中如果出现异常，系统会自动生成一个 Exception 对象，Java 运行时环境寻找能够处理







### 





当Java运行时环境收到异常对象时，会寻找能处理该异常对象的catch块，如果找到合适的catch块，则把该异常对象交给该catch块处理，这个过程被称为捕获(catch)异常。每个catch块都是专门用于处理指定*异常类及其子类*的异常实例。当程序进入负责异常处理的catch块时，系统生成的异常对象将会传给catch块后的异常形参，从而允许catch块通过该对象来获得异常的详细信息。

如果Java运行时环境找不到捕获异常的catch块，则运行时环境终止，Java程序也将退出。

注：*try**块里声明的变量是代码块内局部变量，它只在try**块内有效，在catch**块中不能访问该变量*。

进行异常捕获时不仅应该把Exception类对应的catch块放在最后，而且所有父类异常的catch块都应该排在子类异常catch块的后面(简称：先处理小异常，再处理大异常)，否则将出现编译错误。









Throwable 类是 Java 中所有错误（Error）和异常（Exception）的父类；

Error 类及其子类描述了程序运行时**系统的内部错误**或者资源耗尽错误，应用程序不会抛出这种类型的对象；

Exception 异常分为两类：一类是 RuntimeException，表示由于**程序错误导致**的异常；另一类是RuntimeException以外的异常，程序本身没有问题，但由于像I/O错误这类问题导致的异常；

![](image/异常类继承关系图.jpg)



## 7.1 checked 异常和 unchecked 异常

**将继承于Error或者RuntimeException的异常称为 unchecked异常，其他的异常称为checked异常**；

Java程序**必须显式处理 checked 异常**，如果程序没有处理 checked 异常，该程序在编译时就会发生错误，无法通过编译；

unchecked 异常无须显式声明抛出，因为 unchecked 异常要么不可控制（Error），要么就应该避免发生（RuntimeException异常）。如果程序需要捕获unchecked异常，也可以使用try..catch块来实现。





# 第九章 异常处理

## 9.1 异常和错误

 

 

 

Checked异常的两种处理方式：

1)   当前方法明确知道如何处理该异常，程序可以使用try...catch块来捕获该异常，然后在对应的catch块中修复该异常；

2)   当前方法不知道如何处理这种异常，应该在定义该方法时使用throws声明抛出该异常。(throws声明抛出异常的思路是，当前方法不知道如何处理这种类型的异常，该异常应该由*上一级调用者处理*，如果main方法也不知道如何处理这种类型的异常，也可以使用throws声明抛出异常，该异常将交给JVM处理。JVM对异常的处理方法是，打印异常的跟踪栈信息，并中止程序运行。)

throws声明抛出异常只能在方法签名中使用，throws可以声明抛出多个异常类，多个异常类之间以逗号隔开。如果某方法调用了一个使用throws抛出checked异常的方法，则需要调用方法来处理该异常，如果调用方法不处理该异常，调用方法也需要抛出该异常；

 



## 9.2 异常处理机制

Java的异常处理机制主要依赖于try、catch、finally、throw和throws五个关键字：

1)   try关键字：后紧跟一个花括号扩起来的代码块(花括号不可省略)，简称try块，它里面放置可能引发异常的代码。

2)   catch后对应异常类型和一个代码块，该代码块用于处理指定的异常类型；

3)   finally块用于回收在try块里打开的物理资源，异常机制会保证finally块总被执行。

4)   throws关键字主要在方法签名中使用，用于声明该方法可能抛出的异常；

5)   throw用于抛出一个实际的异常，throw可以单独作为语句使用，抛出一个具体的异常对象。



### 2.   多异常捕获

一个catch块可以捕获多种类型的异常；

捕获多种类型的异常时，多种异常类型之间用竖线“|”隔开。

捕获多种类型的异常时，异常变量有隐式的final修饰，因此程序不能对异常变量重新赋值。

### 3.   使用finally回收资源

程序如果在try块里打开了一些物理资源(例如数据库连接、网络连接和磁盘文件等)，这些物理资源都*必须显式回收*。|

Java的垃圾回收机制不会回收任何物理资源，垃圾回收时仅能回收堆内存中对象占用的内存。

finally块总会被执行。

异常处理语法结构中只有try块是必需的，catch块和finally块至少出现其中之一；

### 4.   自动关闭资源的try语句

在try关键字后紧跟一对圆括号，圆括号可以声明、初始化一个或多个资源，此处的资源指的是那些必须在程序结束时显式关闭的资源，try语句在该语句结束时自动关闭这些资源。

为了保证try语句可以正常关闭资源，这些资源实现类必须实现AutoCloseable或Closeable接口，实现这两个接口就必须实现close()方法。

  try(  //声明、初始化两个可关闭的资源  //try语句句会自动关闭这两个资源  BufferedReader br = new  BufferedReader(new FileReader("AutoCloseTest.java"));  PrintStream ps = new  PrintStream(new FileOutputStream("a.txt")))  {  //使用两个资源  System.out.println(br.readLine());  ps.println("庄生晓梦迷蝴蝶");  }  

 

### 5.   访问异常信息

异常类都继承了Throwable类，Throwable类定义了访问异常信息的方法；

1)   String getMessage()

返回该异常的详细描述字符串；

String toString()方法返回：“该异常对象的类的名字+ ： + getLocalizedMessage()方法返回值”；

2)   Throwable getCause()

如果调用该方法的异常对象有一个导致其产生的异常对象，将返回一个异常对象；

3)   Throwable initCause(Throwable cause)

将调用该方法的异常对象的原因设为指定的异常对象；

4)   void printStackTrace()

将该异常的堆栈轨迹信息输出到标准错误输出。

5)   void printStackTrace(PrintStream\PrintWriter s)

将该异常的跟踪栈信息输出到指定输出流。

6)   StackTraceElement[] getStackTrace()

获得构造这个异常对象时调用堆栈的跟踪；

  **import** java.io.FileInputStream;  **import** java.io.FileNotFoundException;  **import** java.io.IOException;     **class** MyException **extends** Exception  {    **public** MyException()     {      **super**();    }        **public** MyException(String message)     {      **super**(message);    }       **public** MyException(String message, Throwable cause)    {      **super**(message, cause);    }         **public** MyException(Throwable cause)     {      **super**(cause);    }    }     **public** **class** Test  {    /*     * 该方法用于读取指定文件的内容     * 如果命名文件不存在，或者由于其他原因无法打开以供读取，则抛出FileNotFoundException异常     * 在该方法中，将FileNotFoundException异常进行包装成一个自定义异常     */    **public** **static** **void** readFile(String name)         **throws** MyException, IOException    {      FileInputStream f = **null**;      **try**      {        f=**new** FileInputStream(name);      }       //将FileNotFoundException异常包装为自定义异常MyException      **catch** (FileNotFoundException e)      {        **throw** **new** MyException("指定的文件不存在或者打不开！！！", e);           }      **finally**      {        **if**(f!=**null**)         f.close();      }       }          **public** **static** **void** main(String[] args)    {      String file="F:\\0010Eclipse\\Test\\Property.txt";      **try**       {        *readFile*(file);      }       **catch** (MyException e)       {        System.***out\***.println(e.getCause().getMessage());        System.***out\***.println(e.getMessage());        e.printStackTrace();           }       **catch** (IOException e)      {        e.printStackTrace();      }    }  }  

 

 



## 9.3 使用throw抛出异常

throw语句抛出的不是异常类，而是一个异常实例；

如果throw语句抛出的异常是Checked异常，则该throw语句要么处于try块里显式捕获该异常，要么放在一个带throws声明抛出的方法中，即把该异常交给该方法的调用者处理；如果throw语句抛出的异常是Runtime异常，该语句无须放在try块里，也无须放在带throws声明抛出的方法中，程序既可以显式使用try...catch来捕获并处理该异常，也可以完全不理会该异常，把该异常交给该方法调用者处理。



## 9.4 自定义异常类

用户自定义异常类都应该继承Exception基类，如果希望自定义RuntimeException异常，则应该继承RuntimeException基类。

定义异常类时通常需要提供两个构造器：一个是无参数的构造器；另一个是带一个字符串参数的构造器，这个字符串将作为该异常对象的描述信息(也就是异常对象的getMessage()方法的返回值)。此外，如果此异常类与一个原因（cause，即导致该异常产生的异常），还应该包含两个构造函数：只有一个Throwable（cause）对象参数的构造器，包含两个参数String(the detail message)和Throwable（cause）的构造器。

  **class** MyException **extends** Exception  {    **public**  MyException()     {      **super**();    }        **public**  MyException(String message)     {      **super**(message);    }       **public**  MyException(String message, Throwable cause)    {      **super**(message, cause);    }         **public**  MyException(Throwable cause)     {      **super**(cause);    }    }  